CREATE TABLE IF NOT EXISTS `Teams` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `league` VARCHAR(255) NOT NULL,
    `team_name` VARCHAR(255) NOT NULL,
    `coach` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);